name: clientes-dev

services:
  mysql-clientes-dev:
    image: mysql:8.4
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_clientes
    ports:
      - "3421:3306"
    volumes:
      - mysql_clientes_dev_data:/var/lib/mysql

volumes:
  mysql_clientes_dev_data: