spring:
  cloud:
    gateway:
      routes:
        #CATALOGO
        - id: catalogo-route
          uri: lb://catalogo
          predicates:
            - Path=/api/v1/categorias/**
        - id: catalogo-instancia
          uri: lb://catalogo
          predicates:
            - Path=/api/v1/catalogo/instancia
        - id: catalogo-swagger
          uri: lb://catalogo
          predicates:
            - Path=/catalogo/swagger-ui/**,/catalogo/v3/api-docs/**
        
        # PRODUCTO
        - id: producto-route
          uri: lb://producto
          predicates:
            - Path=/api/v1/productos/**
        - id: producto-instancia
          uri: lb://producto
          predicates:
            - Path=/api/v1/producto/instancia
        - id: producto-swagger
          uri: lb://producto
          predicates:
            - Path=/producto/swagger-ui/**,/producto/v3/api-docs/**

        # INVENTARIO
        - id: inventario-route
          uri: lb://inventario
          predicates:
            - Path=/api/v1/inventario/**
        - id: inventario-instancia
          uri: lb://inventario
          predicates:
            - Path=/api/v1/inventario/instancia

        # VENTAS
        - id: ventas-route
          uri: lb://ventas
          predicates:
            - Path=/api/v1/ventas/**
            - Header=X-ROLE,(ADMIN|CAJA)
        - id: ventas-instancia
          uri: lb://ventas
          predicates:
            - Path=/api/v1/ventas/instancia

        # CLIENTES
        - id: clientes-route
          uri: lb://clientes
          predicates:
            - Path=/api/v1/clientes/**
            - Header=X-ROLE,(ADMIN|CAJA)
        - id: clientes-instancia
          uri: lb://clientes
          predicates:
            - Path=/api/v1/clientes/instancia
        - id: clientes-swagger
          uri: lb://clientes
          predicates:
            - Path=/clientes/swagger-ui/**,/clientes/v3/api-docs/**

        # CARRITO
        - id: carrito-route
          uri: lb://carrito
          predicates:
            - Path=/api/v1/carrito/**
            - Header=X-ROLE,(ADMIN|CAJA)
        - id: carrito-instancia
          uri: lb://carrito
          predicates:
            - Path=/api/v1/carrito/instancia
        - id: carrito-swagger
          uri: lb://carrito
          predicates:
            - Path=/carrito/swagger-ui/**,/carrito/v3/api-docs/**

        # PAGOS
        - id: pagos-route
          uri: lb://pagos
          predicates:
            - Path=/api/v1/pagos/**
            - Header=X-ROLE,(ADMIN|CAJA)
        - id: pagos-instancia
          uri: lb://pagos
          predicates:
            - Path=/api/v1/pagos/instancia
        - id: pagos-swagger
          uri: lb://pagos
          predicates:
            - Path=/pagos/swagger-ui/**,/pagos/v3/api-docs/**

        # PROVEEDORES
        - id: proveedores-route
          uri: lb://proveedores
          predicates:
            - Path=/api/v1/proveedores/**
            - Header=X-ROLE,(ADMIN|ALMACEN)
        - id: proveedores-instancia
          uri: lb://proveedores
          predicates:
            - Path=/api/v1/proveedores/instancia
        - id: proveedores-swagger
          uri: lb://proveedores
          predicates:
            - Path=/proveedores/swagger-ui/**,/proveedores/v3/api-docs/**

        # COMPRAS
        - id: compras-route
          uri: lb://compras
          predicates:
            - Path=/api/v1/compras/**
            - Header=X-ROLE,(ADMIN|ALMACEN)
        - id: compras-instancia
          uri: lb://compras
          predicates:
            - Path=/api/v1/compras/instancia
        - id: compras-swagger
          uri: lb://compras
          predicates:
            - Path=/compras/swagger-ui/**,/compras/v3/api-docs/**

        # AUTH
        - id: auth-route
          uri: lb://auth
          predicates:
            - Path=/api/v1/auth/**
        - id: auth-instancia
          uri: lb://auth
          predicates:
            - Path=/api/v1/auth/instancia
        - id: auth-swagger
          uri: lb://auth
          predicates:
            - Path=/auth/swagger-ui/**,/auth/v3/api-docs/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7081/eureka

management:
  endpoints:
    web:
      exposure:
        include: "*"