name: ventas-dev

services:
  mysql-ventas-dev:
    image: mysql:8.4
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_ventas
    ports:
      - "3411:3306" # Tu máquina (cliente externo) -> MySQL dev
    volumes:
      - mysql_ventas_dev_data:/var/lib/mysql

volumes:
  mysql_ventas_dev_data: